// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2eev9sGar2mwhAd9jJp24-rT_KU7qU0',
    appId: '1:162974868808:web:30e49cd9723696106e3f7d',
    messagingSenderId: '162974868808',
    projectId: 'kaiaskin-4ea5a',
    authDomain: 'kaiaskin-4ea5a.firebaseapp.com',
    storageBucket: 'kaiaskin-4ea5a.firebasestorage.app',
    measurementId: 'G-CHD8R37G9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnK1HFbDcMSNSKtDy3ixA3__KXKtRBets',
    appId: '1:162974868808:android:6a0d9dcb80bb28ff6e3f7d',
    messagingSenderId: '162974868808',
    projectId: 'kaiaskin-4ea5a',
    storageBucket: 'kaiaskin-4ea5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1GzzfERPwICigXd2heAkPb8n5nWAyKFQ',
    appId: '1:162974868808:ios:c59041950e4b10346e3f7d',
    messagingSenderId: '162974868808',
    projectId: 'kaiaskin-4ea5a',
    storageBucket: 'kaiaskin-4ea5a.firebasestorage.app',
    iosBundleId: 'com.example.kaiaSkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1GzzfERPwICigXd2heAkPb8n5nWAyKFQ',
    appId: '1:162974868808:ios:c59041950e4b10346e3f7d',
    messagingSenderId: '162974868808',
    projectId: 'kaiaskin-4ea5a',
    storageBucket: 'kaiaskin-4ea5a.firebasestorage.app',
    iosBundleId: 'com.example.kaiaSkin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy2eev9sGar2mwhAd9jJp24-rT_KU7qU0',
    appId: '1:162974868808:web:d1305cb9b3ec049d6e3f7d',
    messagingSenderId: '162974868808',
    projectId: 'kaiaskin-4ea5a',
    authDomain: 'kaiaskin-4ea5a.firebaseapp.com',
    storageBucket: 'kaiaskin-4ea5a.firebasestorage.app',
    measurementId: 'G-42D1MQ2WS0',
  );

}